name: CI

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'Semantic Version (major minor patch)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Validate version input
        run: |
          if [[ "${{ github.event.inputs.newversion }}" != "major" && "${{ github.event.inputs.newversion }}" != "minor" && "${{ github.event.inputs.newversion }}" != "patch" ]]; then
            echo "Invalid input: ${{ github.event.inputs.newversion }}. Only 'major', 'minor', or 'patch' are allowed."
            exit 1
          fi
      - name: Continue with the workflow
        run: echo "Version input is valid:" ${{ github.event.inputs.newversion }}
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Lint and build
        run: npm run lint && npm run build

      - name: Up version
        run: npm version ${{ github.event.inputs.newversion }}

      - name: Publish to npm
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
